DESCRIPTION
===========
sourcecode-scanner project aims to provide a lexical analyser for C-like programming language 
source code which is automatically generated by flex (fast lexical analyser generator).